### ISSUE TITLE
Install MZDK takes 5m recompiling packages

### ISSUE THREAD

**Issue by morgenman** [kmaasrud/brain#1]
I am trying to use this github actions script for my personal notes, but for some reason when it runs, Installing MZDK takes about 5m. 
When looking at it, it seems like it's recompiling MZDK, and all dependencies. 
Is this expected?
Thank you!

**Comment by kmaasrud** [comment]
Sadly, yes. This is to be expected. I have not setup any caching in this action.

We are working on a unified GH Actions workflow that will get published to [the docs](https://mdzk.app/docs) as soon as we feel we've found something that suits most people's use case. In the meantime, you can have a look at our [docs-publish action](https://github.com/mdzk-rs/mdzk/blob/main/.github/workflows/docs-publish.yml), which may be closer to what you want.

If you have any further issues with mdzk, please submit that issue [here](https://github.com/mdzk-rs/mdzk/issues), as this repo is meant purely for hosting the content of my PKM.

**Comment by morgenman** [comment]
Yup, I solved this by putting a local copy of the second to last binary (last one wasn't compiled for linux), and running it locally. 
>5m to 45s
