### ISSUE TITLE
Backlinks does not work for local [[references]]

### ISSUE THREAD

**Issue by morgenman** [kmaasrud/brain#2]
Not sure if this belongs here or in mdzk...
I recently got this all up and running with some customizations [here](https://morgenman.github.io/Computer-Science/). 
What I noticed is that the backlink system does not handle folders very well. 
Example folder structure:
```
A.md
B.md
Folder 1 
|   C.md
|   D.md
```
A.md can reference [[B]] and it will show up in B.html as a backlink on the bottom. 
A.md can reference [[Folder1/C]] and it will show up in C.html as a backlink. 
However,  C cannot reference [[D]] and still have it show up in D.html as a backlink. 

If you like, feel free to see how I have it set up in the following repository:
[https://github.com/morgenman/Computer-Science/tree/brain](https://github.com/morgenman/Computer-Science/tree/brain)

I've already dealt with a lot of the shortcomings with this implementation, most of which are implemented by editing the md files before running mdzk (take a look at the github action on the master branch of that repository). 

Is there any way to get local references working?

**Comment by kmaasrud** [comment]
Firstly, this definitely belongs in [the mdzk repo](https://github.com/mdzk-rs/mdzk) 😅 

Secondly, thank you for informing me about this issue! I just tried reproducing your scenario and builing with mdzk HEAD, and I get the same issue as you describe. I am pretty confident this is a fault in how we inject backlinks using regexes, so this will most likely get fixed once we rewrite our backlinks preprocessor (which is next on the todo-list). However, I'm gonna open a new issue on mdzk so we can keep track of it.
